SELECT nombre FROM producto;
SELECT nombre,precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio * 1.12 FROM producto;
SELECT nombre AS 'nom de producto', precio, precio * 1.12 FROM producto;
SELECT UPPER(nombre),precio FROM producto;
SELECT LOWER(nombre),precio FROM producto;
SELECT nombre,UPPER(LEFT(nombre,2)) FROM producto;
SELECT nombre, CEILING(precio) FROM producto;
SELECT nombre, TRUNCATE(precio,0) FROM producto;
SELECT fabricante.codigo FROM fabricante INNER JOIN producto ON producto.codigo_fabricante = fabricante.codigo;
SELECT distinct fabricante.codigo FROM fabricante INNER JOIN producto ON producto.codigo_fabricante = fabricante.codigo;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre,precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante WHERE ROW_NUM >=4 LIMIT 2;
SELECT nombre,precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre,precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre FROM producto WHERE producto.codigo_fabricante = 2;
SELECT p.nombre, p.precio, f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC;
SELECT p.codigo, p.nombre,f.codigo, f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio,f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre, p.precio,f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo ORDER BY p.precio DESC LIMIT 1;
SELECT * from producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre = 'Lenovo';
SELECT * FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE p.precio >200 AND f.nombre = 'Crucial';
SELECT * FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate';
SELECT * FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN('Asus','Hewlett-Packard','Seagate');
SELECT p.nombre,p.precio FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e';
SELECT p.nombre,p.precio FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%';
SELECT p.nombre,p.precio,f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, f.nombre ASC;
SELECT DISTINCT f.codigo,f.nombre FROM fabricante AS f INNER JOIN producto AS p ON f.codigo = p.codigo_fabricante;
SELECT DISTINCT f.codigo,f.nombre,p.* FROM fabricante AS f LEFT JOIN producto AS p ON f.codigo = p.codigo_fabricante;
SELECT f.codigo,f.nombre FROM fabricante AS f LEFT JOIN producto AS p  ON p.codigo_fabricante = f.codigo WHERE f.codigo NOT IN (SELECT codigo_fabricante FROM producto);
SELECT producto.* FROM producto,fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = 'Lenovo';
SELECT producto.* FROM producto WHERE producto.precio > (SELECT precio FROM producto,fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = 'Lenovo' ORDER BY fabricante.nombre LIMIT 1);
SELECT p.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo' ORDER BY f.nombre LIMIT 1;
SELECT p.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Hewlett-Packard' ORDER BY f.nombre DESC LIMIT 1;
SELECT p.* FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE (p.precio >= (SELECT AVG(precio) FROM producto,fabricante WHERE producto.codigo_fabricante = fabricante.codigo))AND f.nombre ='Asus';
-- AMBIGUA